apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
    spec:
      containers:
      - name: conversao
        image: gru.ocir.io/grglog7bpvjm/conversao-temperatura:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversao
  annotations:
    oci.oraclecloud.com/load-balancer-shape: "flexible"
    oci.oraclecloud.com/load-balancer-shape-flex-min: "10"
    oci.oraclecloud.com/load-balancer-shape-flex-max: "100"
spec:
  selector:
    app: conversao
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer